### ISSUE TITLE
[Request/Discussion] Moving the client to he CloudFoundry Foundation Org

### ISSUE THREAD

**Issue by vipinvkmenon** [cloudfoundry/go-cfclient#379]
Hi,

Since this repo has a lot of active usage and development and considering the language/library popularity. Does it make sense to move the cf-goclient under the CloudFoundry Foundation Org, so that it becomes a more "official" client that can be consumed.

This I believe will also help in the maintaining the standards that are maintained for the other repos that are part of the Foundations.

**Comment by sneal** [comment]
Good idea. I will look into doing this.

**Comment by beyhan** [comment]
The first step would be to open a pr for the CFF [community](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/app-runtime-interfaces.md?plain=1#L389-L402) repo which suggest to add this repository to the App Runtime Interfaces WG. Most probably a new area like the [Java Tools](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/app-runtime-interfaces.md?plain=1#L389-L402) makes sense. In the pr we can have further discussions.

**Comment by sneal** [comment]
This is now complete
