### ISSUE TITLE
Missing fields in stack resource

### ISSUE THREAD

**Issue by Dray56** [cloudfoundry/go-cfclient#423]
According to the cloudfoundry [docs](https://v3-apidocs.cloudfoundry.org/version/3.167.0/index.html#the-stack-object), there are fields present such as build_rootfs_image, default etc. However the resource does not contain the fields. Also description can be null so it should be made as a pointer
```go
type Stack struct {
	Name             string    `json:"name"`
	Description      string   `json:"description"`
	Metadata         *Metadata `json:"metadata"`
	Resource         `json:",inline"`
}
```

**Comment by sneal** [comment]
Looks like the cloud controller added support for having a different rootfs for staging vs running sometime last year.

**Comment by sneal** [comment]
https://github.com/cloudfoundry/cloud_controller_ng/pull/3328
