### ISSUE TITLE
How to get application instances details in v3?

### ISSUE THREAD

**Issue by yosi83** [cloudfoundry/go-cfclient#434]
Hi,

I upgraded my code to use v3. In the previous version, I was able to get the instances of the App via App.Instances.
How can I get it in v3? I didn't find any function for that.

Thanks,
Yossi Kunya

**Comment by metskem** [comment]
You can get that info by calling the Processes endpoint, for example with the [Processes.ListForAppAll](https://github.com/cloudfoundry/go-cfclient/blob/79b9c386a7fcbffe3fcf46c12cc79520e6f8e55c/client/process.go#L120) : 

`	processes, err := cfClient.Processes.ListForAppAll(
		context.Background(),
		appGuid,
		&client.ProcessListOptions{
			AppGUIDs: client.Filter{Values: []string{appGuid}},
		})
`

**Comment by yosi83** [comment]
Thanks, It's working!
