### ISSUE TITLE
No interface provided for `Client`

### ISSUE THREAD

**Issue by geigerj0** [cloudfoundry/go-cfclient#436]
The `go-cfclient` library, specifically the `client.go`-file in, does not define an interface for its client: https://github.com/cloudfoundry/go-cfclient/blob/c4d222641ae3b169358ac84f081604c48432c519/client/client.go#L23

This design choice makes it challenging for developers to use the library in their projects effectively, particularly when writing unit tests. Without an exposed interface, it becomes cumbersome to generate mocks for the client.

**Comment by sneal** [comment]
Typically in Go you define interfaces in the consumer code rather than in the library like Java or C#. Is there any reason that wouldn't work for you?

**Comment by geigerj0** [comment]
I thought that it's common to offer interfaces along the library. Thanks for pointing this out that it doesn't make sense in Go! 👍
